cfn-template.yml
---
AWSTemplateFormatVersion: ""2010-09-09""

Description: >
  This template creates Kittens Carousel App on EC@ instance
  It also creates a security group allowing HTTP (Port 80) and 
  SSH (22) Connections from anywhere

Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Enable HTTP for Apache Web Server
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: String
      InstanceInitiatedShutdownBehavior: String
      InstanceType: String
      KeyName: String
      SecurityGroupIds: 
        - String
      Tags: 
        - Tag
      UserData: String

Outputs:
  set of outputs